{
  "artifacts": [],
  "command": "bc_run",
  "experiment": {
    "base_dir": "/home/mzhao2/long_term_adaptation/human_aware_rl/human_aware_rl/lta_ppo",
    "dependencies": [
      "ale-py==0.7.3",
      "matplotlib==3.5.0",
      "memory-profiler==0.60.0",
      "numpy==1.21.5",
      "sacred==0.7.4",
      "seaborn==0.9.0",
      "tensorflow-gpu==2.0.0"
    ],
    "mainfile": "train_model_on_bc_only.py",
    "name": "PPO",
    "repositories": [
      {
        "commit": "dde512943314df8e316c6fd5c4de3d62a89f9481",
        "dirty": true,
        "url": "git@github.com:HelloN00bman/human_aware_rl.git"
      }
    ],
    "sources": [
      [
        "train_model_on_bc_only.py",
        "_sources/train_model_on_bc_only_549d4cc46736e314681b311e4e9f3ec8.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 511, in _apply_op_helper\n    preferred_dtype=default_dtype)\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 1175, in internal_convert_to_tensor\n    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 977, in _TensorTensorConversionFunction\n    (dtype.name, t.dtype.name, str(t)))\n",
    "ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int64: 'Tensor(\"ArgMax:0\", shape=(1200,), dtype=int64, device=/device:GPU:0)'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/sacred-0.7.4-py3.7.egg/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"../lta_ppo/train_model_on_bc_only.py\", line 286, in bc_run\n    model = create_model(gym_env, \"ppo_agent\", **params)\n",
    "  File \"../../human_aware_rl/baselines_utils_for_lta.py\", line 479, in create_model\n    network_kwargs=kwargs\n",
    "  File \"/home/mzhao2/long_term_adaptation/human_aware_rl/baselines/baselines/ppo3/ppo3.py\", line 126, in learn_human_model\n    max_grad_norm=max_grad_norm, scope=scope)\n",
    "  File \"/home/mzhao2/long_term_adaptation/human_aware_rl/baselines/baselines/ppo3/model.py\", line 113, in __init__\n    human_pred_loss = tf.square(human_A-human_model_prediction)\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py\", line 812, in binary_op_wrapper\n    return func(x, y, name=name)\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 9536, in sub\n    \"Sub\", x=x, y=y, name=name)\n",
    "  File \"/home/mzhao2/anaconda3/envs/lta_overcooked/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 547, in _apply_op_helper\n    inferred_from[input_arg.type_attr]))\n",
    "TypeError: Input 'y' of 'Sub' Op has type int64 that does not match type float32 of argument 'x'.\n"
  ],
  "heartbeat": "2022-02-17T03:01:28.136995",
  "host": {
    "ENV": {},
    "cpu": "AMD Ryzen Threadripper 2990WX 32-Core Processor",
    "gpus": {
      "driver_version": "465.19.01",
      "gpus": [
        {
          "model": "NVIDIA GeForce RTX 2080 Ti",
          "persistence_mode": true,
          "total_memory": 11019
        },
        {
          "model": "NVIDIA GeForce RTX 2080 Ti",
          "persistence_mode": true,
          "total_memory": 11016
        }
      ]
    },
    "hostname": "forte",
    "os": [
      "Linux",
      "Linux-5.4.0-94-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.7.11"
  },
  "meta": {
    "command": "bc_run",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "EX_NAME=testing_lta",
        "layout_name=simple",
        "REW_SHAPING_HORIZON=1e6",
        "PPO_RUN_TOT_TIMESTEPS=8e6",
        "LR=1e-3",
        "GPU_ID=0",
        "OTHER_AGENT_TYPE=bc_train",
        "SEEDS=[9456, 1887, 5578, 5987,  516]",
        "VF_COEF=0.5",
        "MINIBATCHES=10",
        "LR_ANNEALING=3",
        "SELF_PLAY_HORIZON=[5e5, 3e6]",
        "TIMESTAMP_DIR=False"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2022-02-17T03:01:21.614168",
  "status": "FAILED",
  "stop_time": "2022-02-17T03:01:28.138752"
}